version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:8000"
#    volumes:
#      - .:/app # абсолютный путь!!!!
#    command: python /app/manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000


