# Generated by Django 4.1 on 2022-08-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pill',
            new_name='Bill',
        ),
    ]
