# Generated by Django 4.1 on 2022-08-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_pill_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
