# Generated by Django 4.1 on 2022-08-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_serviceclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='service_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.serviceclass'),
            preserve_default=False,
        ),
    ]
